### ISSUE TITLE
Getting info on Teachers.

### ISSUE THREAD

**Issue by TylerShago** [MTM6330-F18/Final--tsunami#1]
This is a test.

**Comment by lamb0203** [comment]
We will interview them next week.

**Comment by schr0205** [comment]
But we will have the questions ready for when we meet with them

**Comment by lamb0203** [comment]
🤦‍♀️. We will interview Michael, Katie and Hussein.

**Comment by leun0077** [comment]
Questions will be made soon~

**Comment by TylerShago** [comment]
Test
