### ISSUE TITLE
Gathering photos and info

### ISSUE THREAD

**Issue by TylerShago** [MTM6330-F18/Final--tsunami#10]

**Comment by lamb0203** [comment]
Robert's Photo
![robert](https://user-images.githubusercontent.com/43186915/49626126-6b9ae200-f9a6-11e8-8d1c-a2fbaa43a978.jpg)

**Comment by lamb0203** [comment]
Michael's Photo 
![michael](https://user-images.githubusercontent.com/43186915/49626140-7ce3ee80-f9a6-11e8-98be-93f908ba9f1b.jpg)
