### ISSUE TITLE
Teacher Interviews #3 

### ISSUE THREAD

**Issue by TylerShago** [MTM6330-F18/Final--tsunami#6]

**Comment by schr0205** [comment]
Full Name:
 Robert L. McKenney

Job Title: 
Professor

Email: 
mckennr@algonquincollege.com

Phone: none

What courses do you teach?
I teach in both the Interactive Media Design (IMD) and Mobile Application Design & Development (MAD&D) programs:
MTM6330 Web Production (IMD)
MTM6430 Web Applications (IMD)

MAD9111 Fundamentals of Computer Hardware and Networking (MAD&D)
MAD9124 Mobile API Development

Where did you go to school university, college, etc.)?
I have studied at Carleton, Laurier and the school of hard knocks ;-)

Why did you become a teacher?
My professional career, has always included coaching and mentoring components. When the opportunity came up to teach at Algonquin this seemed like a natural extension. I really enjoy the opportunity to share my knowledge and passion for our industry with the next generation of web design and development professionals.

How many years have you been a teacher?
I have been formally teaching at Algonquin for two years. I have been coach colleagues over my whole 30 year career.

Is there anything you wish you taught but can't?
I would love to add a special course dedicated to implementing web accessibility best practices. I think this is an important and often overlooked topic in our industry.

Advice for future students:
Come with an open mind. Don’t be afraid of what you don’t know -- yet. If you are a little uncomfortable, that means that you are learning something new and that is a good thing. We can guide you through the learning process, and if you are willing to do the reading and the practice you can learn to do anything!
